const CONFIG = {
    introTitle: 'Bình à!',
    introDesc: `Chắc m đang bối rồi dell hiểu cái j đang xảy ra đúng không :))`,
    btnIntro: 'ĐÚNG VẬY',
    title: 'Tui có 1 điều muốn nói là 😙',
    desc: 'T THÍCH M ',
    btnYes: 'Yêu anh <33',
    btnNo: 'Không, ai gảnh =))',
    question:'Trên thế giới hơn 7 tỉ người mà sao em lại yêu anh <3',
    btnReply: 'Gửi cho anh <3',
    reply: 'Yêu anh 3000 <33',
    mess: 'T xàm á, ai gảnh yêu :))) ',
    messDesc: 'Lo học đi nha bé. Bớt bớt lại ',
    btnAccept: 'Okiiiii lun <3',
}
