const CONFIG = {
    introTitle: 'Ê nhóc!',
    introDesc: `M dạo này học hành sao rồi :))`,
    btnIntro: 'Ai biết =))',
    title: 'Tui có 1 điều muốn nói là 😙',
    desc: 'Không học mốt bốc đất mà ăn ',
    btnYes: 'Học thì học',
    btnNo: 'Có cc =))',
    question:'Lo mà học đi nha con đizz',
    btnReply: 'Viết ý kiến cho t',
    reply: 'Cản ơn m đã giúp t',
    mess: 'Dume, chuyện. Anh em mà:))) ',
    messDesc: 'Lo học đi nha bé. Bớt bớt lại ',
    btnAccept: 'Okiiiii lun <3',
}
